import type { SectionDefinition } from '@/types/sections';

export const gallerySectionDefinition: SectionDefinition = {
  type: 'gallery',
  name: 'Image Gallery',
  description: 'Product image gallery with lightbox and thumbnails',
  icon: 'Images',
  category: 'Media',
  defaultSettings: {
    title: 'Product Gallery',
    layout: 'grid',
    columns: 3,
    gap: 16,
    showThumbnails: true,
    enableLightbox: true,
    aspectRatio: '1:1',
    imageSource: 'product',
    showTitle: true,
  },
  settingsSchema: [
    {
      key: 'title',
      label: 'Section Title',
      type: 'text',
      default: 'Product Gallery',
      placeholder: 'Enter section title',
      description: 'Title displayed above the gallery',
    },
    {
      key: 'showTitle',
      label: 'Show Title',
      type: 'toggle',
      default: true,
      description: 'Display the section title',
    },
    {
      key: 'layout',
      label: 'Layout',
      type: 'select',
      default: 'grid',
      options: [
        { value: 'grid', label: 'Grid' },
        { value: 'masonry', label: 'Masonry' },
        { value: 'carousel', label: 'Carousel' },
      ],
      description: 'Gallery layout style',
    },
    {
      key: 'columns',
      label: 'Columns',
      type: 'range',
      default: 3,
      min: 2,
      max: 6,
      step: 1,
      description: 'Number of columns in grid layout',
    },
    {
      key: 'gap',
      label: 'Gap (px)',
      type: 'range',
      default: 16,
      min: 0,
      max: 48,
      step: 4,
      description: 'Space between images',
    },
    {
      key: 'aspectRatio',
      label: 'Aspect Ratio',
      type: 'select',
      default: '1:1',
      options: [
        { value: '1:1', label: 'Square (1:1)' },
        { value: '4:3', label: 'Landscape (4:3)' },
        { value: '16:9', label: 'Widescreen (16:9)' },
        { value: '3:4', label: 'Portrait (3:4)' },
        { value: 'auto', label: 'Original' },
      ],
      description: 'Image aspect ratio',
    },
    {
      key: 'enableLightbox',
      label: 'Enable Lightbox',
      type: 'toggle',
      default: true,
      description: 'Allow clicking images for full-size view',
    },
    {
      key: 'imageSource',
      label: 'Image Source',
      type: 'select',
      default: 'product',
      options: [
        { value: 'product', label: 'Product Images' },
        { value: 'custom', label: 'Custom Images' },
      ],
      description: 'Source of gallery images',
    },
  ],
};

