import type { SectionDefinition } from '@/types/sections';

export const heroSectionDefinition: SectionDefinition = {
  type: 'hero',
  name: 'Hero Banner',
  description: 'Large hero section with headline, subheading, image, and CTA button',
  icon: 'ImageIcon',
  category: 'Content',
  defaultSettings: {
    headline: 'Premium Quality Product',
    subheading: 'Experience the difference with our carefully crafted products',
    ctaText: 'Shop Now',
    ctaLink: '/collections/all',
    imagePosition: 'right',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    overlayOpacity: 0,
    height: 'large',
    useProductImage: true,
  },
  settingsSchema: [
    {
      key: 'headline',
      label: 'Headline',
      type: 'text',
      default: 'Premium Quality Product',
      placeholder: 'Enter headline text',
      description: 'Main headline text for the hero section',
    },
    {
      key: 'subheading',
      label: 'Subheading',
      type: 'textarea',
      default: 'Experience the difference with our carefully crafted products',
      placeholder: 'Enter subheading text',
      description: 'Supporting text below the headline',
    },
    {
      key: 'ctaText',
      label: 'Button Text',
      type: 'text',
      default: 'Shop Now',
      placeholder: 'Enter button text',
      description: 'Text displayed on the call-to-action button',
    },
    {
      key: 'ctaLink',
      label: 'Button Link',
      type: 'text',
      default: '/collections/all',
      placeholder: '/collections/all',
      description: 'URL the button links to',
    },
    {
      key: 'imagePosition',
      label: 'Image Position',
      type: 'select',
      default: 'right',
      options: [
        { value: 'left', label: 'Left' },
        { value: 'right', label: 'Right' },
        { value: 'background', label: 'Background' },
      ],
      description: 'Position of the image relative to text',
    },
    {
      key: 'height',
      label: 'Section Height',
      type: 'select',
      default: 'large',
      options: [
        { value: 'small', label: 'Small (400px)' },
        { value: 'medium', label: 'Medium (600px)' },
        { value: 'large', label: 'Large (800px)' },
      ],
      description: 'Height of the hero section',
    },
    {
      key: 'backgroundColor',
      label: 'Background Color',
      type: 'color',
      default: '#f9fafb',
      description: 'Background color for the hero section',
    },
    {
      key: 'textColor',
      label: 'Text Color',
      type: 'color',
      default: '#111827',
      description: 'Color of the headline and subheading text',
    },
    {
      key: 'overlayOpacity',
      label: 'Overlay Opacity',
      type: 'range',
      default: 0,
      min: 0,
      max: 1,
      step: 0.1,
      description: 'Opacity of dark overlay (for background images)',
    },
    {
      key: 'useProductImage',
      label: 'Use Product Image',
      type: 'toggle',
      default: true,
      description: 'Use the main product image as hero image',
    },
  ],
};

